import Head from "next/head"
import { useTranslation } from "react-i18next"
import { useRouter } from "next/router"
import Link from "next/link"
export default function Home() {
  const router = useRouter()
  const { t } = useTranslation()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-3xl 380:text-2xl dark:bg-black dark:text-white">
        <Link href="auth/login" className="text-2xl text-center mt-4 cursor-pointer ">
          login right now
        </Link>
      </main>
      <div>
        <Link href="about">about</Link>
      </div>
      <div>
        <Link href="login">login</Link>
      </div>
      <div>
        <Link href="/login">/login</Link>
      </div>
      <div>
        <Link href="auth">auth</Link>
      </div>
      <div>
        <Link href="/auth">/auth</Link>
      </div>
      <div>
        <Link href="/social/newsfeed">link to newsfeed</Link>
      </div>
      <div onClick={() => router.push("/social/newsfeed")}>router to newsfeed</div>
    </>
  )
}
