import { t } from "i18next";
import Head from "next/head";
import { useTranslation } from "react-i18next";
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  const { t } = useTranslation();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-3xl 380:text-2xl dark:bg-black dark:text-white">
        <div
          onClick={() => router.push("/auth/login")}
          className="text-2xl text-center mt-4 cursor-pointer"
        >
          login
        </div>
      </main>
    </>
  );
}
